### ISSUE TITLE
La data al momento del response muestra caracteres de signo de interrogacion en caracteres con acentos 

### ISSUE THREAD

**Issue by Hermandell** [GDSC-UANL/siase-api#10]
![error](https://user-images.githubusercontent.com/67210536/144658399-cd204dbf-6b57-466d-98b4-5efcb242b4e6.jpg)

Tendria que pasar la data en alguna otra codificacion ya sea charset : UTF-8 , =iso-8859-1 etc..

**Comment by Fmaldonado6** [comment]
El issue ya se ha corregido en el [commit](https://github.com/GDSC-UANL/siase-api/commit/80108c3bb26215416483940dc44bdc4aaaf60a40) de la rama de development, gracias por reportar el issue!
