### ISSUE TITLE
Agregar una mejor landing page

### ISSUE THREAD

**Issue by Fmaldonado6** [GDSC-UANL/siase-api#4]
Actualmente la ruta principal solo regresa "SIASE API", lo ideal sería poner un poco de información de la API como las rutas, los creadores, etc. Algo parecido a la api de [Jikan](https://api.jikan.moe/v3)

**Comment by FabianCruz-0** [comment]
Está en progreso. La landing tendrá un poco más de diseño que la de Jikan.

**Comment by Fmaldonado6** [comment]
Landing page agregada en [pull request](https://github.com/GDSC-UANL/siase-api/pull/6)
