### ISSUE TITLE
Hora errónea en materias de horas seguidas

### ISSUE THREAD

**Issue by FabianCruz-0** [GDSC-UANL/siase-api#9]
Cuando hay una materia que tiene varias clases seguidas, ejemplo:
![image](https://user-images.githubusercontent.com/57044771/144649303-b02f010c-20ad-4b66-a1e4-ca664ed91757.png)

La API retorna el número de clases correcto, sin embargo, en la hora de las clases solo retorna la última hora de la clase, no la que le corresponde a cada una, ejemplo de respuesta de API:

![image](https://user-images.githubusercontent.com/57044771/144649153-f361b94b-c2ae-4f20-8c64-7120825ac47a.png)

**Comment by Fmaldonado6** [comment]
Bug resuelto en commit [c73c78c](https://github.com/GDSC-UANL/siase-api/commit/c73c78c4c0f6cb727cba44653a9c299c0644d81a) en rama de development
